name = "libdictenstein"
version = "4.0.0"
license = "Apache-2.0"
author = "Dylon Edwards"
maintainer = "Dylon Edwards <dylon.devo@gmail.com>"
description = "High-performance dictionaries and trie-maps for approximate string matching."

[library]
source-dir = "src"

[dependencies]
vinary-tree-interop = { path = "../../../vinary-tree-interop/bindings/fortran" }

[build]
link = ["libdictenstein"]
module-naming = false
