name = "vinary-tree-libdictenstein"
version = "4.0.0"
license = "Apache-2.0"
author = "Dylon Edwards"
maintainer = "Dylon Edwards <dylon.devo@gmail.com>"
description = "High-performance modular dictionary backends"
homepage = "https://github.com/vinary-tree/libdictenstein"

[library]
source-dir = "src"

[dependencies.vinary-tree-interop]
namespace = "vinary-tree"
v = "4.0.0"

[build]
link = ["libdictenstein"]
module-naming = true
