include_guard(GLOBAL)
include(CMakeFindDependencyMacro)
find_dependency(Threads)
find_dependency(vinary-tree-interop 4.0 CONFIG)
get_filename_component(_LDICT_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

if(NOT TARGET libdictenstein::shared)
  add_library(libdictenstein::shared SHARED IMPORTED)
  set_target_properties(libdictenstein::shared PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${_LDICT_PREFIX}/include" INTERFACE_LINK_LIBRARIES "vinary-tree::interop")
  if(WIN32)
    set_target_properties(libdictenstein::shared PROPERTIES IMPORTED_LOCATION "${_LDICT_PREFIX}/bin/libdictenstein.dll" IMPORTED_IMPLIB "${_LDICT_PREFIX}/lib/libdictenstein.dll.lib")
  elseif(APPLE)
    set_target_properties(libdictenstein::shared PROPERTIES IMPORTED_LOCATION "${_LDICT_PREFIX}/lib/liblibdictenstein.dylib")
  else()
    set_target_properties(libdictenstein::shared PROPERTIES IMPORTED_LOCATION "${_LDICT_PREFIX}/lib/liblibdictenstein.so")
  endif()
endif()

if(NOT TARGET libdictenstein::static)
  add_library(libdictenstein::static STATIC IMPORTED)
  set_target_properties(libdictenstein::static PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${_LDICT_PREFIX}/include" INTERFACE_COMPILE_DEFINITIONS LDICT_STATIC INTERFACE_LINK_LIBRARIES "vinary-tree::interop")
  if(WIN32)
    set_target_properties(libdictenstein::static PROPERTIES IMPORTED_LOCATION "${_LDICT_PREFIX}/lib/libdictenstein.lib" INTERFACE_LINK_LIBRARIES "bcrypt;userenv;ws2_32;ntdll;synchronization;advapi32;Threads::Threads")
  elseif(APPLE)
    find_library(_LDICT_ICONV_LIBRARY NAMES iconv REQUIRED)
    find_library(_LDICT_COREFOUNDATION_FRAMEWORK NAMES CoreFoundation REQUIRED)
    find_library(_LDICT_SECURITY_FRAMEWORK NAMES Security REQUIRED)
    set_target_properties(libdictenstein::static PROPERTIES IMPORTED_LOCATION "${_LDICT_PREFIX}/lib/liblibdictenstein.a" INTERFACE_LINK_LIBRARIES "${CMAKE_DL_LIBS};Threads::Threads;m;${_LDICT_ICONV_LIBRARY};${_LDICT_COREFOUNDATION_FRAMEWORK};${_LDICT_SECURITY_FRAMEWORK}")
  else()
    set_target_properties(libdictenstein::static PROPERTIES IMPORTED_LOCATION "${_LDICT_PREFIX}/lib/liblibdictenstein.a" INTERFACE_LINK_LIBRARIES "${CMAKE_DL_LIBS};Threads::Threads;m")
  endif()
endif()

if(NOT DEFINED LIBDICTENSTEIN_LINKAGE)
  set(LIBDICTENSTEIN_LINKAGE "SHARED")
endif()
string(TOUPPER "${LIBDICTENSTEIN_LINKAGE}" _LDICT_LINKAGE)
if(NOT _LDICT_LINKAGE STREQUAL "SHARED" AND NOT _LDICT_LINKAGE STREQUAL "STATIC")
  message(FATAL_ERROR "LIBDICTENSTEIN_LINKAGE must be SHARED or STATIC")
endif()
if(NOT TARGET libdictenstein::libdictenstein)
  add_library(libdictenstein::libdictenstein INTERFACE IMPORTED)
  if(_LDICT_LINKAGE STREQUAL "STATIC")
    set_property(TARGET libdictenstein::libdictenstein PROPERTY INTERFACE_LINK_LIBRARIES libdictenstein::static)
  else()
    set_property(TARGET libdictenstein::libdictenstein PROPERTY INTERFACE_LINK_LIBRARIES libdictenstein::shared)
  endif()
endif()
set(libdictenstein_FOUND TRUE)
unset(_LDICT_LINKAGE)
unset(_LDICT_PREFIX)
